name: staging test

on:
  push:
    branches: [staging]

jobs:
  test:
    runs-on: [self-hosted,nodebuilder]
    steps:
      - uses: actions/checkout@v3
      - name: create node hello image
        run: docker build -t hello nodeHello/

